[build]
  command = "npm run build-all-themes"

[context.2022]
  publish = "builds/2022/"

[context.2021]
  publish = "builds/2021/"

[context.2020]
  publish = "builds/2020/"
  
[context.2019]
  publish = "builds/2019/"

[context.2018]
  publish = "builds/2018/"

[context.2016]
  publish = "builds/2017/"
